  AWSTemplateFormatVersion: "2010-09-09"
  Description: Setup DNS CAA Records to allow only AWS to generate certs
  Parameters:
    ZoneId: 
      Type: String
      Description: Enter a zone to add CAA records to
    Domain: 
      Type: String
      Description: Enter domain to use for the CAA records
  Resources: 
    CAARecord:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !Ref ZoneId
        Name: !Join [ ., [ !Ref Domain, '']] 
        Type: CAA
        TTL: '3600'
        ResourceRecords:
        - '0 issue "amazon.com;"'
        - '0 issue "amazontrust.com;"'
        - '0 issue "awstrust.com;"'
        - '0 issue "amazonaws.com;"'
        