  AWSTemplateFormatVersion: "2010-09-09"
  Resources: 
    CAARecord:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !ImportValue PrimaryHostedZoneId
        Name: !Join [ ., [ !ImportValue PrimaryDomain, '']] 
        Type: CAA
        TTL: '3600'
        ResourceRecords:
        - '0 issue "amazon.com;"'
        - '0 issue "amazontrust.com;"'
        - '0 issue "awstrust.com;"'
        - '0 issue "amazonaws.com;"'
        